# Generated by Django 4.2.24 on 2026-01-28 02:26
# SIMPLIFIED: Removed constraint/index removals for non-existent variation fields

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_alter_printer_options'),
        ('products', '0015_alter_itemvariation_cost_alter_itemvariation_price_and_more'),
        ('inventory', '0005_remove_batch_unique_batch_variation_outlet_and_more'),
    ]

    operations = [
        # Only keep the AddField and meaningful AlterUniqueTogether operations
        # Skip constraint/index removals since variation support was never fully created
        migrations.AddField(
            model_name='locationstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_stocks', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='locationstock',
            unique_together={('product', 'outlet')},
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeitem',
            unique_together={('stock_take', 'product')},
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['outlet'], name='inventory_b_outlet__90c2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='locationstock',
            index=models.Index(fields=['product', 'outlet'], name='inventory_l_product_656169_idx'),
        ),
        migrations.AddIndex(
            model_name='locationstock',
            index=models.Index(fields=['product'], name='inventory_l_product_136835_idx'),
        ),
    ]
