# Generated by Django 4.2.24 on 2026-01-28 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_alter_printer_options'),
        ('products', '0015_alter_itemvariation_cost_alter_itemvariation_price_and_more'),
        ('inventory', '0005_remove_batch_unique_batch_variation_outlet_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stocktakeitem',
            name='unique_stocktake_variation',
        ),
        migrations.RemoveConstraint(
            model_name='stocktakeitem',
            name='unique_stocktake_product',
        ),
        migrations.RemoveIndex(
            model_name='batch',
            name='inventory_b_variati_ea7ea7_idx',
        ),
        migrations.RemoveIndex(
            model_name='batch',
            name='inventory_b_variati_1eecd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='locationstock',
            name='inventory_l_variati_401c0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='locationstock',
            name='inventory_l_variati_967a4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='inventory_s_variati_312169_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocktakeitem',
            name='inventory_s_variati_4ad843_idx',
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='locationstock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='variation',
        ),
        migrations.AddField(
            model_name='locationstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_stocks', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='locationstock',
            unique_together={('product', 'outlet')},
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeitem',
            unique_together={('stock_take', 'product')},
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['outlet'], name='inventory_b_outlet__90c2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='locationstock',
            index=models.Index(fields=['product', 'outlet'], name='inventory_l_product_656169_idx'),
        ),
        migrations.AddIndex(
            model_name='locationstock',
            index=models.Index(fields=['product'], name='inventory_l_product_136835_idx'),
        ),
        migrations.RemoveField(
            model_name='batch',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='locationstock',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='stocktakeitem',
            name='variation',
        ),
    ]
