# Generated by Django 4.2.24 on 2026-01-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_itemvariation_unique_together_and_more'),
        ('outlets', '0005_alter_printer_options'),
        ('inventory', '0006_remove_stocktakeitem_unique_stocktake_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('product', 'outlet', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product', 'outlet'], name='inventory_b_product_a73c09_idx'),
        ),
    ]
