# Generated by Django 4.2.28 on 2026-02-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_itemvariation_unique_together_and_more'),
        ('inventory', '0008_remove_batch_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product affected by this movement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product in this stock take count', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_items', to='products.product'),
        ),
    ]
