# Generated by Django 4.2.28 on 2026-04-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefronts', '0002_storefrontevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storefront',
            new_name='storefronts_tenant__43bf27_idx',
            old_name='storefronts_tenant__0ed79f_idx',
        ),
        migrations.RenameIndex(
            model_name='storefront',
            new_name='storefronts_slug_943873_idx',
            old_name='storefronts_slug_985d17_idx',
        ),
        migrations.RenameIndex(
            model_name='storefrontcatalogrule',
            new_name='storefronts_storefr_0e3126_idx',
            old_name='storefronts_storefr_378434_idx',
        ),
        migrations.RenameIndex(
            model_name='storefrontdomain',
            new_name='storefronts_domain_c715ad_idx',
            old_name='storefronts_domain_1eb84f_idx',
        ),
        migrations.RenameIndex(
            model_name='storefrontevent',
            new_name='storefronts_storefr_50253e_idx',
            old_name='storefronts_storefr_created_19f90a_idx',
        ),
        migrations.RenameIndex(
            model_name='storefrontevent',
            new_name='storefronts_storefr_aa2faf_idx',
            old_name='storefronts_storefr_event_n_a757f8_idx',
        ),
        migrations.RenameIndex(
            model_name='storefrontorder',
            new_name='storefronts_storefr_300989_idx',
            old_name='storefronts_storefr_88695f_idx',
        ),
        migrations.RenameIndex(
            model_name='storefrontorder',
            new_name='storefronts_public__063c5c_idx',
            old_name='storefronts_public__450f24_idx',
        ),
    ]
