# Generated by Django 4.2.28 on 2026-03-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_outlet_role'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffoutletrole',
            new_name='staff_outle_staff_i_4abd05_idx',
            old_name='staff_outle_staff_i_idx',
        ),
        migrations.RenameIndex(
            model_name='staffoutletrole',
            new_name='staff_outle_outlet__00d7e3_idx',
            old_name='staff_outle_outlet_idx',
        ),
    ]
