# Generated by Django 4.2.7 on 2026-04-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_staff_outle_staff_i_idx_staff_outle_staff_i_4abd05_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_storefront',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_switch_outlet',
            field=models.BooleanField(default=True),
        ),
    ]
