# Generated by Django 4.2.7 on 2026-04-17 00:00

from django.db import migrations, models


def seed_distribution_permissions(apps, schema_editor):
    Role = apps.get_model('staff', 'Role')
    distribution_enabled_names = {'admin', 'manager', 'dispatcher', 'driver'}

    for role in Role.objects.all():
        role_name = (role.name or '').strip().lower()
        if role_name in distribution_enabled_names:
            role.can_distribution = True
            role.save(update_fields=['can_distribution'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_add_storefront_switch_outlet_to_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_distribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_pos_bar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='can_pos_restaurant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='can_pos_retail',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(seed_distribution_permissions, noop_reverse),
    ]
