# Generated by Django 4.2.28 on 2026-04-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_permission_codes_rbac'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='permissiondefinition',
            new_name='staff_permi_module_9d2fb4_idx',
            old_name='staff_permi_module_bfda2d_idx',
        ),
        migrations.RenameIndex(
            model_name='permissiondefinition',
            new_name='staff_permi_is_acti_049650_idx',
            old_name='staff_permi_is_acti_8f90ca_idx',
        ),
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='staff_role__role_id_d94580_idx',
            old_name='staff_role__role_id_5c2d2b_idx',
        ),
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='staff_role__permiss_0096f6_idx',
            old_name='staff_role__permiss_d0f388_idx',
        ),
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='staff_role__allowed_000f61_idx',
            old_name='staff_role__allowed_47ddd5_idx',
        ),
    ]
