# Generated by Django 4.2.30 on 2026-04-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_shift'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_categor_fcaba7_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
