# Generated by Django 4.2 on 2026-03-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("outlets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity_type", models.CharField(max_length=120)),
                ("entity_id", models.CharField(max_length=128)),
                ("operation", models.CharField(max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("outlet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sync_change_logs", to="outlets.outlet")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sync_change_logs", to="tenants.tenant")),
            ],
            options={
                "verbose_name": "Sync Change Log",
                "verbose_name_plural": "Sync Change Logs",
                "db_table": "sync_change_log",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProcessedClientEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_event_id", models.CharField(max_length=128)),
                ("event_type", models.CharField(max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("accepted", "Accepted"), ("duplicate", "Duplicate"), ("rejected", "Rejected")], default="accepted", max_length=20)),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(auto_now=True)),
                ("outlet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processed_sync_events", to="outlets.outlet")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="processed_sync_events", to="tenants.tenant")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processed_sync_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Processed Client Event",
                "verbose_name_plural": "Processed Client Events",
                "db_table": "sync_processed_client_event",
                "ordering": ["-created_at"],
                "unique_together": {("tenant", "client_event_id")},
            },
        ),
        migrations.AddIndex(
            model_name="syncchangelog",
            index=models.Index(fields=["tenant", "id"], name="sync_change_tenant__d2731b_idx"),
        ),
        migrations.AddIndex(
            model_name="syncchangelog",
            index=models.Index(fields=["tenant", "created_at"], name="sync_change_tenant__82f2ca_idx"),
        ),
        migrations.AddIndex(
            model_name="syncchangelog",
            index=models.Index(fields=["entity_type", "entity_id"], name="sync_change_entity__929029_idx"),
        ),
        migrations.AddIndex(
            model_name="processedclientevent",
            index=models.Index(fields=["tenant", "client_event_id"], name="sync_proce_tenant__f2dd0d_idx"),
        ),
        migrations.AddIndex(
            model_name="processedclientevent",
            index=models.Index(fields=["tenant", "created_at"], name="sync_proce_tenant__62ec41_idx"),
        ),
        migrations.AddIndex(
            model_name="processedclientevent",
            index=models.Index(fields=["status"], name="sync_proce_status_51e5a5_idx"),
        ),
    ]
