# Generated by Django 4.2 on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedclientevent",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="processedclientevent",
            name="last_error",
            field=models.TextField(blank=True),
        ),
    ]
