# Generated by Django 4.2.28 on 2026-04-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_processedclientevent_retry_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processedclientevent',
            new_name='sync_proces_tenant__ba0c91_idx',
            old_name='sync_proce_tenant__f2dd0d_idx',
        ),
        migrations.RenameIndex(
            model_name='processedclientevent',
            new_name='sync_proces_tenant__39c070_idx',
            old_name='sync_proce_tenant__62ec41_idx',
        ),
        migrations.RenameIndex(
            model_name='processedclientevent',
            new_name='sync_proces_status_90d687_idx',
            old_name='sync_proce_status_51e5a5_idx',
        ),
        migrations.RenameIndex(
            model_name='syncchangelog',
            new_name='sync_change_tenant__fb1a36_idx',
            old_name='sync_change_tenant__d2731b_idx',
        ),
        migrations.RenameIndex(
            model_name='syncchangelog',
            new_name='sync_change_tenant__66dea0_idx',
            old_name='sync_change_tenant__82f2ca_idx',
        ),
        migrations.RenameIndex(
            model_name='syncchangelog',
            new_name='sync_change_entity__c2d980_idx',
            old_name='sync_change_entity__929029_idx',
        ),
    ]
