# Generated by Django 4.2.7 on 2026-05-17 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync', '0003_rename_sync_proce_tenant__f2dd0d_idx_sync_proces_tenant__ba0c91_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedclientevent',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedclientevent',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_sync_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processedclientevent',
            name='edited_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='processedclientevent',
            name='marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processedclientevent',
            name='original_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='processedclientevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('applied', 'Applied'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
