# Generated by Django 4.2.28 on 2026-04-28 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0004_cashmovementandsupportfields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashmovement',
            options={'ordering': ['created_at'], 'verbose_name': 'Cash Movement', 'verbose_name_plural': 'Cash Movements'},
        ),
        migrations.RenameIndex(
            model_name='cashmovement',
            new_name='shifts_cash_shift_i_cd9a06_idx',
            old_name='shifts_cashmovement_shift_idx',
        ),
        migrations.RenameIndex(
            model_name='cashmovement',
            new_name='shifts_cash_movemen_490ad6_idx',
            old_name='shifts_cashmovement_type_idx',
        ),
        migrations.RenameIndex(
            model_name='cashmovement',
            new_name='shifts_cash_created_69ca49_idx',
            old_name='shifts_cashmovement_created_idx',
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='closed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who closed this shift (may differ from opener)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shift',
            name='variance_approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who signed off the variance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variance_approved_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shift',
            name='variance_reason',
            field=models.TextField(blank=True, help_text='Explanation required when |variance| > threshold'),
        ),
    ]
