# Generated by Django 4.2.28 on 2026-02-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='delivery',
            new_name='distributio_tenant__f9101d_idx',
            old_name='distributio_tenant__2def2b_idx',
        ),
        migrations.RenameIndex(
            model_name='delivery',
            new_name='distributio_sale_id_a180db_idx',
            old_name='distributio_sale_id_37026d_idx',
        ),
        migrations.RenameIndex(
            model_name='delivery',
            new_name='distributio_status_2d50cc_idx',
            old_name='distributio_status_b39f50_idx',
        ),
        migrations.RenameIndex(
            model_name='delivery',
            new_name='distributio_driver__89d075_idx',
            old_name='distributio_driver__e5336c_idx',
        ),
        migrations.RenameIndex(
            model_name='delivery',
            new_name='distributio_vehicle_9f3acf_idx',
            old_name='distributio_vehicle_0ac3d1_idx',
        ),
        migrations.RenameIndex(
            model_name='delivery',
            new_name='distributio_tenant__23b8d4_idx',
            old_name='distributio_tenant__8c3208_idx',
        ),
        migrations.RenameIndex(
            model_name='driverprofile',
            new_name='distributio_tenant__82e0fd_idx',
            old_name='distributio_tenant__336136_idx',
        ),
        migrations.RenameIndex(
            model_name='driverprofile',
            new_name='distributio_is_acti_f4bcc8_idx',
            old_name='distributio_is_acti_9ba334_idx',
        ),
        migrations.RenameIndex(
            model_name='driverprofile',
            new_name='distributio_tenant__be78a6_idx',
            old_name='distributio_tenant__2ea90f_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='distributio_tenant__d3c031_idx',
            old_name='distributio_tenant__9a0ee5_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='distributio_is_acti_4c46ac_idx',
            old_name='distributio_is_acti_3f9ca5_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='distributio_tenant__6b97a9_idx',
            old_name='distributio_tenant__12ad4c_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclelocation',
            new_name='distributio_tenant__fc6295_idx',
            old_name='distributio_tenant__5db5c2_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclelocation',
            new_name='distributio_vehicle_b56824_idx',
            old_name='distributio_vehicle_4c39aa_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclelocation',
            new_name='distributio_deliver_08cc62_idx',
            old_name='distributio_delivery_1e15fd_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclelocation',
            new_name='distributio_recorde_9bc90f_idx',
            old_name='distributio_recorde_d8daf2_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclelocation',
            new_name='distributio_tenant__a387b5_idx',
            old_name='distributio_tenant__d12d0c_idx',
        ),
    ]
