# Generated by Django 4.2.28 on 2026-03-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_fleet_trip_deliveryorder_upgrade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deliveryorder',
            new_name='distributio_tenant__dd7aa0_idx',
            old_name='distributio_tenant__114928_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryorder',
            new_name='distributio_deliver_7f55c8_idx',
            old_name='distributio_deliver_e7ce05_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryorder',
            new_name='distributio_tenant__2f4af4_idx',
            old_name='distributio_tenant__1cc704_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryorder',
            new_name='distributio_sales_o_dd01ba_idx',
            old_name='distributio_sales_o_d5fa1d_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryorder',
            new_name='distributio_warehou_1ad1f1_idx',
            old_name='distributio_warehou_c7f3e0_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryorderitem',
            new_name='distributio_tenant__0691b8_idx',
            old_name='distributio_tenant__8ca1ad_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryorderitem',
            new_name='distributio_deliver_ef328d_idx',
            old_name='distributio_deliver_3f7640_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryorderitem',
            new_name='distributio_product_60731b_idx',
            old_name='distributio_product_8e8fe1_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryorderitem',
            new_name='distributio_is_rele_2d7dad_idx',
            old_name='distributio_is_rele_750ad3_idx',
        ),
        migrations.RenameIndex(
            model_name='driver',
            new_name='distributio_tenant__d43683_idx',
            old_name='distributio_tenant__dbfa8c_idx',
        ),
        migrations.RenameIndex(
            model_name='driver',
            new_name='distributio_status_693d80_idx',
            old_name='distributio_status_d052bc_idx',
        ),
        migrations.RenameIndex(
            model_name='driver',
            new_name='distributio_tenant__22aadc_idx',
            old_name='distributio_tenant__fe405a_idx',
        ),
        migrations.RenameIndex(
            model_name='trip',
            new_name='distributio_tenant__42cb0c_idx',
            old_name='distributio_tenant__58ee7b_idx',
        ),
        migrations.RenameIndex(
            model_name='trip',
            new_name='distributio_deliver_2340b9_idx',
            old_name='distributio_deliver_a3d579_idx',
        ),
        migrations.RenameIndex(
            model_name='trip',
            new_name='distributio_vehicle_e79aba_idx',
            old_name='distributio_vehicle_934762_idx',
        ),
        migrations.RenameIndex(
            model_name='trip',
            new_name='distributio_driver__9a1857_idx',
            old_name='distributio_driver__385378_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='distributio_status_023eeb_idx',
            old_name='distributio_status_306766_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='distributio_tenant__c8489d_idx',
            old_name='distributio_tenant__8e309e_idx',
        ),
    ]
