# Generated by Django 4.2.24 on 2025-12-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_item_variation_model'),
        ('suppliers', '0003_purchaseorder_purchaseorderitem_purchasereturn_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Deprecated: Use variation instead. Kept for backward compatibility.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='products.product'),
        ),
    ]
