# Generated by Django 4.2.24 on 2025-12-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_item_variation_model'),
        ('suppliers', '0003_purchaseorder_purchaseorderitem_purchasereturn_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Deprecated: Use variation instead. Kept for backward compatibility.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['variation'], name='suppliers_p_variati_8df48d_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variation__isnull', False)), fields=('purchase_order', 'variation'), name='unique_po_variation'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('variation__isnull', True)), fields=('purchase_order', 'product'), name='unique_po_product'),
        ),
    ]
