# Generated by Django 4.2.24 on 2025-12-07 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_create_default_variations'),
        ('suppliers', '0005_autopurchaseordersettings_productsupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPOAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('draft_created', 'Draft PO Created'), ('draft_updated', 'Draft PO Updated'), ('item_added', 'Item Added to Draft'), ('item_updated', 'Item Updated in Draft'), ('quantity_recalculated', 'Quantity Recalculated'), ('duplicate_prevented', 'Duplicate Draft Prevented'), ('low_stock_detected', 'Low Stock Detected'), ('sales_velocity_calculated', 'Sales Velocity Calculated'), ('check_triggered', 'Low Stock Check Triggered')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data (stock levels, quantities, velocities, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, help_text='Related product (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_po_audit_logs', to='products.product')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Related purchase order (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='suppliers.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, help_text='Related supplier (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_po_audit_logs', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_po_audit_logs', to='tenants.tenant')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered the action (null for automatic)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_po_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto-PO Audit Log',
                'verbose_name_plural': 'Auto-PO Audit Logs',
                'db_table': 'suppliers_autopoauditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant'], name='suppliers_a_tenant__cf199d_idx'), models.Index(fields=['purchase_order'], name='suppliers_a_purchas_ee015d_idx'), models.Index(fields=['product'], name='suppliers_a_product_2a34d2_idx'), models.Index(fields=['supplier'], name='suppliers_a_supplie_c66680_idx'), models.Index(fields=['action_type'], name='suppliers_a_action__d0415f_idx'), models.Index(fields=['created_at'], name='suppliers_a_created_257b31_idx')],
            },
        ),
    ]
