# Generated by Django 4.2.7 on 2025-12-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_make_supplier_optional_in_po'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseorderitem',
            name='unique_po_product_supplier',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseorderitem',
            name='unique_po_product_no_supplier',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderitem',
            new_name='suppliers_p_supplie_620340_idx',
            old_name='suppliers_p_supplie_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderitem',
            new_name='suppliers_p_supplie_993f97_idx',
            old_name='suppliers_p_supplie_status_idx',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_supplier', 'Pending Supplier'), ('pending', 'Pending'), ('approved', 'Approved'), ('ready_to_order', 'Ready to Order'), ('ordered', 'Ordered'), ('received', 'Received'), ('partial', 'Partially Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('purchase_order', 'product', 'supplier'), name='unique_po_product_supplier'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('supplier__isnull', True)), fields=('purchase_order', 'product'), name='unique_po_product_no_supplier'),
        ),
    ]
