# Generated by Django 4.2.7 on 2026-01-19 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_remove_purchaseorderitem_unique_po_product_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopurchaseordersettings',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='supplier',
        ),

        migrations.AlterUniqueTogether(
            name='purchasereturnitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='purchase_order_item',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='purchase_return',
        ),
        migrations.RemoveField(
            model_name='productsupplier',
            name='reorder_point',
        ),
        migrations.RemoveField(
            model_name='productsupplier',
            name='reorder_quantity',
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='is_preferred',
            field=models.BooleanField(default=False, help_text='Preferred supplier for this product'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Optional: Can be assigned later.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='suppliers.supplier'),
        ),
        migrations.DeleteModel(
            name='AutoPOAuditLog',
        ),
        migrations.DeleteModel(
            name='AutoPurchaseOrderSettings',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.DeleteModel(
            name='PurchaseReturnItem',
        ),
    ]
