# Generated by Django 4.2.28 on 2026-02-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_purchasereturnitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchasereturnitem',
            new_name='suppliers_p_tenant__972a13_idx',
            old_name='suppliers_purchasereturnitem_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasereturnitem',
            new_name='suppliers_p_purchas_3c8f46_idx',
            old_name='suppliers_purchasereturnitem_preturn_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasereturnitem',
            new_name='suppliers_p_product_63b9bf_idx',
            old_name='suppliers_purchasereturnitem_product_idx',
        ),
    ]
