# Generated by Django 4.2.7 on 2026-01-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_credit_enabled_customer_credit_limit_and_more'),
        ('sales', '1001_remove_sale_sales_till_idx'),
        ('tenants', '0005_add_logo_field'),
        ('shifts', '0002_shift_device_id_shift_sync_status_and_more'),
        ('outlets', '0005_alter_printer_options'),
        ('restaurant', '0003_kitchenorderticket_till'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('order_type', models.CharField(choices=[('dine_in', 'Dine In'), ('takeout', 'Takeout'), ('delivery', 'Delivery')], default='dine_in', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=20, null=True)),
                ('discount_reason', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Money'), ('credit', 'Credit/On Account')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('guests', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Restaurant Order',
                'verbose_name_plural': 'Restaurant Orders',
                'db_table': 'restaurant_restaurantorder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='kitchenorderticket',
            name='restaurant_till_idx',
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='outlets.outlet'),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_order', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='shifts.shift'),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='restaurant.table'),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='till',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='outlets.till'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['tenant'], name='restaurant__tenant__560b24_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['outlet'], name='restaurant__outlet__118889_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['table'], name='restaurant__table_i_662c56_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['status'], name='restaurant__status_4b474b_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['created_at'], name='restaurant__created_d7720a_idx'),
        ),
    ]
