from django.urls import path

from .views import (
    ProductImportCancelView,
    ProductImportApproveView,
    ProductImportApplyView,
    ProductImportErrorsView,
    ProductImportHistoryView,
    ProductImportMissingProductsView,
    ProductImportPreviewView,
    ProductImportRecoverView,
    ProductImportRollbackExecuteView,
    ProductImportRollbackPreviewView,
    ProductImportRowUpdateView,
    ProductImportRowsView,
    ProductImportSourceDownloadView,
    ProductImportStatusView,
    StockTakeImportApplyView,
    StockTakeImportHistoryView,
    StockTakeImportPreviewView,
    StockTakeImportReopenView,
    StockTakeImportRowsView,
    StockTakeImportRowUpdateView,
    StockTakeImportSourceDownloadView,
    StockTakeImportStatusView,
)

urlpatterns = [
    path('imports/products/history/', ProductImportHistoryView.as_view(), name='imports-products-history'),
    path('imports/products/preview/', ProductImportPreviewView.as_view(), name='imports-products-preview'),
    path('imports/products/<uuid:batch_id>/approve/', ProductImportApproveView.as_view(), name='imports-products-approve'),
    path('imports/products/<uuid:batch_id>/cancel/', ProductImportCancelView.as_view(), name='imports-products-cancel'),
    path('imports/products/<uuid:batch_id>/recover/', ProductImportRecoverView.as_view(), name='imports-products-recover'),
    path('imports/products/<uuid:batch_id>/rollback-preview/', ProductImportRollbackPreviewView.as_view(), name='imports-products-rollback-preview'),
    path('imports/products/<uuid:batch_id>/rollback/', ProductImportRollbackExecuteView.as_view(), name='imports-products-rollback'),
    path('imports/products/<uuid:batch_id>/apply/', ProductImportApplyView.as_view(), name='imports-products-apply'),
    path('imports/products/<uuid:batch_id>/status/', ProductImportStatusView.as_view(), name='imports-products-status'),
    path('imports/products/<uuid:batch_id>/errors/', ProductImportErrorsView.as_view(), name='imports-products-errors'),
    path('imports/products/<uuid:batch_id>/rows/', ProductImportRowsView.as_view(), name='imports-products-rows'),
    path('imports/products/<uuid:batch_id>/rows/<int:row_number>/', ProductImportRowUpdateView.as_view(), name='imports-products-row-update'),
    path('imports/products/<uuid:batch_id>/missing/', ProductImportMissingProductsView.as_view(), name='imports-products-missing'),
    path('imports/products/<uuid:batch_id>/source/', ProductImportSourceDownloadView.as_view(), name='imports-products-source-download'),

    path('imports/stock-takes/<int:stock_take_id>/preview/', StockTakeImportPreviewView.as_view(), name='imports-stock-takes-preview'),
    path('imports/stock-takes/<int:stock_take_id>/history/', StockTakeImportHistoryView.as_view(), name='imports-stock-takes-history'),
    path('imports/stock-takes/<uuid:batch_id>/status/', StockTakeImportStatusView.as_view(), name='imports-stock-takes-status'),
    path('imports/stock-takes/<uuid:batch_id>/rows/', StockTakeImportRowsView.as_view(), name='imports-stock-takes-rows'),
    path('imports/stock-takes/<uuid:batch_id>/rows/<int:row_number>/', StockTakeImportRowUpdateView.as_view(), name='imports-stock-takes-row-update'),
    path('imports/stock-takes/<uuid:batch_id>/source/', StockTakeImportSourceDownloadView.as_view(), name='imports-stock-takes-source-download'),
    path('imports/stock-takes/<uuid:batch_id>/reopen/', StockTakeImportReopenView.as_view(), name='imports-stock-takes-reopen'),
    path('imports/stock-takes/<uuid:batch_id>/apply/', StockTakeImportApplyView.as_view(), name='imports-stock-takes-apply'),
]
