# Generated by Django 4.2.24 on 2026-01-22 13:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0005_alter_printer_options'),
        ('customers', '0002_customer_credit_enabled_customer_credit_limit_and_more'),
        ('tenants', '0005_add_logo_field'),
        ('sales', '0011_receipttemplate_alter_deliveryitem_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0014_rename_products_pr_outlet_idx_products_pr_outlet__655c0b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(help_text="Table number or seat identifier (e.g., 'Table 5', 'Bar Seat 3')", max_length=50)),
                ('table_type', models.CharField(choices=[('table', 'Table'), ('bar_seat', 'Bar Counter Seat'), ('booth', 'Booth'), ('patio', 'Patio'), ('vip', 'VIP Area')], default='table', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=2, help_text='Maximum seating capacity')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, help_text='e.g., Main Bar, Patio, VIP Lounge', max_length=255)),
                ('position_x', models.IntegerField(default=0, help_text='X position on floor plan')),
                ('position_y', models.IntegerField(default=0, help_text='Y position on floor plan')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bar Table',
                'verbose_name_plural': 'Bar Tables',
                'db_table': 'bar_table',
                'ordering': ['table_type', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tab_number', models.CharField(db_index=True, help_text='Auto-generated tab number', max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, help_text="Customer name for display (e.g., 'John', 'Guy in red shirt')", max_length=255)),
                ('customer_phone', models.CharField(blank=True, help_text='Contact phone for callbacks', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed tab amount (optional)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, help_text='Bartender who closed the tab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabs_closed', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Linked customer account (for credit tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bar_tabs', to='customers.customer')),
                ('merged_into', models.ForeignKey(blank=True, help_text='If merged, the tab this was merged into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_tabs', to='bar.tab')),
                ('opened_by', models.ForeignKey(help_text='Bartender who opened the tab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabs_opened', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bar_tabs', to='outlets.outlet')),
                ('sale', models.OneToOneField(blank=True, help_text='Final sale created when tab is closed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_tab', to='sales.sale')),
                ('table', models.ForeignKey(blank=True, help_text='Current table assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabs_history', to='bar.bartable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_tabs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Bar Tab',
                'verbose_name_plural': 'Bar Tabs',
                'db_table': 'bar_tab',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TabTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('from_table', models.ForeignKey(blank=True, help_text='Previous table (null if was walk-up)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='bar.bartable')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='bar.tab')),
                ('to_table', models.ForeignKey(blank=True, help_text='New table (null if becoming walk-up)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='bar.bartable')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tab Transfer',
                'verbose_name_plural': 'Tab Transfers',
                'db_table': 'bar_tab_transfer',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='TabMerge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_total', models.DecimalField(decimal_places=2, help_text='Total of source tab at time of merge', max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('merged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab_merges', to=settings.AUTH_USER_MODEL)),
                ('source_tab', models.ForeignKey(help_text='The tab that was merged (and closed)', on_delete=django.db.models.deletion.CASCADE, related_name='merged_into_records', to='bar.tab')),
                ('target_tab', models.ForeignKey(help_text='The tab that received merged items', on_delete=django.db.models.deletion.CASCADE, related_name='merge_records', to='bar.tab')),
            ],
            options={
                'verbose_name': 'Tab Merge',
                'verbose_name_plural': 'Tab Merges',
                'db_table': 'bar_tab_merge',
                'ordering': ['-merged_at'],
            },
        ),
        migrations.AddField(
            model_name='bartable',
            name='current_tab',
            field=models.OneToOneField(blank=True, help_text='Currently active tab at this table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_table', to='bar.tab'),
        ),
        migrations.AddField(
            model_name='bartable',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bar_tables', to='outlets.outlet'),
        ),
        migrations.AddField(
            model_name='bartable',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_tables', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='TabItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Special instructions, modifiers')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(help_text='Bartender who added this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab_items_added', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tab_items', to='products.product')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bar.tab')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab_items', to='products.productunit')),
                ('voided_by', models.ForeignKey(blank=True, help_text='Bartender who voided this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab_items_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tab Item',
                'verbose_name_plural': 'Tab Items',
                'db_table': 'bar_tab_item',
                'ordering': ['added_at'],
                'indexes': [models.Index(fields=['tab'], name='bar_tab_ite_tab_id_364c38_idx'), models.Index(fields=['product'], name='bar_tab_ite_product_5882db_idx'), models.Index(fields=['added_by'], name='bar_tab_ite_added_b_79350c_idx'), models.Index(fields=['added_at'], name='bar_tab_ite_added_a_627f72_idx'), models.Index(fields=['is_voided'], name='bar_tab_ite_is_void_343831_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tab',
            index=models.Index(fields=['tenant'], name='bar_tab_tenant__42cd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='tab',
            index=models.Index(fields=['outlet'], name='bar_tab_outlet__6a5ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='tab',
            index=models.Index(fields=['status'], name='bar_tab_status_c93732_idx'),
        ),
        migrations.AddIndex(
            model_name='tab',
            index=models.Index(fields=['opened_at'], name='bar_tab_opened__674b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='tab',
            index=models.Index(fields=['tab_number'], name='bar_tab_tab_num_39d21c_idx'),
        ),
        migrations.AddIndex(
            model_name='tab',
            index=models.Index(fields=['customer'], name='bar_tab_custome_e70395_idx'),
        ),
        migrations.AddIndex(
            model_name='bartable',
            index=models.Index(fields=['tenant'], name='bar_table_tenant__9ef120_idx'),
        ),
        migrations.AddIndex(
            model_name='bartable',
            index=models.Index(fields=['outlet'], name='bar_table_outlet__ae11a6_idx'),
        ),
        migrations.AddIndex(
            model_name='bartable',
            index=models.Index(fields=['status'], name='bar_table_status_f5741d_idx'),
        ),
        migrations.AddIndex(
            model_name='bartable',
            index=models.Index(fields=['table_type'], name='bar_table_table_t_6c2a63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bartable',
            unique_together={('tenant', 'outlet', 'number')},
        ),
    ]
