# Generated by Django 4.2.28 on 2026-02-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_logo_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_sales', models.BooleanField(default=True, help_text='Enable Sales app')),
                ('allow_pos', models.BooleanField(default=True, help_text='Enable POS app')),
                ('allow_inventory', models.BooleanField(default=True, help_text='Enable Inventory app')),
                ('allow_office', models.BooleanField(default=True, help_text='Enable Office app')),
                ('allow_settings', models.BooleanField(default=True, help_text='Enable Settings app')),
                ('allow_sales_create', models.BooleanField(default=True, help_text='Create new sales')),
                ('allow_sales_refund', models.BooleanField(default=True, help_text='Process refunds')),
                ('allow_sales_reports', models.BooleanField(default=True, help_text='View sales reports')),
                ('allow_pos_restaurant', models.BooleanField(default=True, help_text='Restaurant POS mode')),
                ('allow_pos_bar', models.BooleanField(default=True, help_text='Bar POS mode')),
                ('allow_pos_retail', models.BooleanField(default=True, help_text='Retail POS mode')),
                ('allow_pos_discounts', models.BooleanField(default=True, help_text='Apply discounts in POS')),
                ('allow_inventory_products', models.BooleanField(default=True, help_text='Manage products')),
                ('allow_inventory_stock_take', models.BooleanField(default=True, help_text='Perform stock take')),
                ('allow_inventory_transfers', models.BooleanField(default=True, help_text='Stock transfers between outlets')),
                ('allow_inventory_adjustments', models.BooleanField(default=True, help_text='Stock adjustments')),
                ('allow_inventory_suppliers', models.BooleanField(default=True, help_text='Manage suppliers')),
                ('allow_office_accounting', models.BooleanField(default=True, help_text='Accounting module')),
                ('allow_office_hr', models.BooleanField(default=True, help_text='HR & Payroll module')),
                ('allow_office_reports', models.BooleanField(default=True, help_text='Office reports')),
                ('allow_office_analytics', models.BooleanField(default=True, help_text='Analytics dashboard')),
                ('allow_settings_users', models.BooleanField(default=True, help_text='Manage users')),
                ('allow_settings_outlets', models.BooleanField(default=True, help_text='Manage outlets')),
                ('allow_settings_integrations', models.BooleanField(default=True, help_text='Third-party integrations')),
                ('allow_settings_advanced', models.BooleanField(default=True, help_text='Advanced settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(help_text='Related tenant', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Permission',
                'verbose_name_plural': 'Tenant Permissions',
                'db_table': 'tenant_permissions',
            },
        ),
    ]
