# Generated by Django 4.2.28 on 2026-03-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenantpaymentrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantpaymentrecord',
            new_name='tenant_paym_tenant__a27784_idx',
            old_name='tenant_paym_tenant__fbb5c3_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantpaymentrecord',
            new_name='tenant_paym_payment_b43176_idx',
            old_name='tenant_paym_payment_f6f5fd_idx',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='currency_symbol',
            field=models.CharField(default='MWK', max_length=10),
        ),
    ]
