# Generated by Django 4.2.7 on 2026-01-28 00:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_products_pr_outlet_idx_products_pr_outlet__655c0b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariation',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price for this variation (optional)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price for this variation', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, help_text='Retail price', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale price', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, help_text='Retail price for this unit', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale price for this unit (optional)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
