# Generated by Django 4.2.24 on 2026-01-28 02:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '1002_remove_saleitem_sales_salei_variati_742672_idx_and_more'),
        ('inventory', '0006_remove_stocktakeitem_unique_stocktake_variation_and_more'),
        ('products', '0015_alter_itemvariation_cost_alter_itemvariation_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemvariation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itemvariation',
            name='product',
        ),
        migrations.RemoveIndex(
            model_name='productunit',
            name='products_pr_unit_na_ab0b33_idx',
        ),
        migrations.AddField(
            model_name='productunit',
            name='low_stock_threshold',
            field=models.IntegerField(default=0, help_text='Low stock alert threshold for this unit', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, help_text='How many base units this unit equals (minimum 1.0 for base unit)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))]),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_745c84_idx'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(check=models.Q(('conversion_factor__gte', 1.0)), name='conversion_factor_min_1', violation_error_message='Conversion factor must be at least 1.0'),
        ),
        migrations.DeleteModel(
            name='ItemVariation',
        ),
    ]
