# Generated by Django 4.2.7 on 2026-02-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_itemvariation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiry date', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateField(blank=True, help_text='Product manufacturing date', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='track_expiration',
            field=models.BooleanField(default=False, help_text='Whether to track expiration for this product'),
        ),
    ]
