# Generated by Django on 2026-02-14

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_add_expiry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preparation_time',
            field=models.IntegerField(blank=True, help_text='Prep time in minutes for restaurant items', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume in milliliters for bar items', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
        migrations.AddField(
            model_name='product',
            name='alcohol_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alcohol percentage for bar items', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator('0'), django.core.validators.MaxValueValidator('100')]),
        ),
    ]
