# Generated by Django 4.2.28 on 2026-02-17 01:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_add_restaurant_bar_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alcohol_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alcohol percentage for bar items', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume in milliliters for bar items', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
