# Generated by Django 4.2.24 on 2025-12-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_item_variation_model'),
        ('sales', '0005_add_delivery_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='variation_name',
            field=models.CharField(blank=True, help_text='Variation name snapshot', max_length=255),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Deprecated: Use variation instead. Kept for backward compatibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='products.product'),
        ),
    ]
