# Generated by Django 4.2.24 on 2026-01-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_receipttemplate_alter_deliveryitem_unique_together_and_more'),
        ('sales', '0999_add_till_field'),
    ]

    operations = [
    ]
