# Generated by Django 4.2.7 on 2026-01-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '1000_merge_20260124_1239'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_till_idx',
        ),
    ]
