# Generated by Django 4.2.24 on 2026-01-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '1001_remove_sale_sales_till_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='saleitem',
            name='sales_salei_variati_742672_idx',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='variation',
        ),
    ]
