# Generated by Django 4.2.28 on 2026-02-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_make_variation_name_nullable'),
        ('sales', '1002_saleitem_discount'),
    ]

    operations = [
    ]
