# Generated by Django 4.2.28 on 2026-02-08 09:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_itemvariation_unique_together_and_more'),
        ('sales', '1004_add_payment_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bank_transfer_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Aggregated bank transfer payments for this sale', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Aggregated card payments for this sale', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Aggregated cash received for this sale', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Aggregated credit-account payments for this sale', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='mobile_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Aggregated mobile-money payments for this sale', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='other_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Aggregated other payments for this sale', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', help_text='Payment status for credit sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tab_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Aggregated tab (on-account) payments for this sale', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product sold', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='products.product'),
        ),
    ]
