# Generated by Django 4.2.28 on 2026-02-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '1005_alter_sale_bank_transfer_amount_and_more'),
        ('sales', '1005_payment_indexes_and_daily_summary'),
    ]

    operations = [
    ]
