# Generated by Django 4.2.28 on 2026-02-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_guests_sale_priority_sale_table_and_more'),
        ('sales', '1007_payment_summary_fix'),
    ]

    operations = [
    ]
