# Generated by Django 4.2.28 on 2026-02-17 01:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '1013_add_saleitem_tax_rate_at_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='is_void',
            field=models.BooleanField(default=False, help_text='Indicates if this sale was voided'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='void_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for voiding a sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tax_rate_at_sale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tax rate captured at time of sale', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
