# Generated by Django 4.2.28 on 2026-03-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '1019_printdevice_pairing_security'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='printdevice',
            new_name='sales_print_tenant__733441_idx',
            old_name='sales_pd_tenant_device_idx',
        ),
        migrations.RenameIndex(
            model_name='printdevice',
            new_name='sales_print_tenant__fe8078_idx',
            old_name='sales_pd_tenant_outlet_active_idx',
        ),
        migrations.RenameIndex(
            model_name='printdevice',
            new_name='sales_print_is_acti_813ebd_idx',
            old_name='sales_pd_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='printdevice',
            new_name='sales_print_last_se_70d156_idx',
            old_name='sales_pd_last_seen_idx',
        ),
        migrations.RenameIndex(
            model_name='printer',
            new_name='sales_print_tenant__a45e9e_idx',
            old_name='sales_pr_tenant_outlet_type_active_idx',
        ),
        migrations.RenameIndex(
            model_name='printer',
            new_name='sales_print_device__1706f6_idx',
            old_name='sales_pr_device_active_idx',
        ),
        migrations.RenameIndex(
            model_name='printjob',
            new_name='sales_print_tenant__15f3c8_idx',
            old_name='sales_pj_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='printjob',
            new_name='sales_print_tenant__c6ff1f_idx',
            old_name='sales_pj_tenant_device_status_idx',
        ),
        migrations.RenameIndex(
            model_name='printjob',
            new_name='sales_print_tenant__8f9659_idx',
            old_name='sales_pj_tenant_outlet_ptype_status_idx',
        ),
        migrations.RenameIndex(
            model_name='printjob',
            new_name='sales_print_outlet__00ce03_idx',
            old_name='sales_pj_outlet_status_idx',
        ),
        migrations.RenameIndex(
            model_name='printjob',
            new_name='sales_print_created_945463_idx',
            old_name='sales_pj_created_idx',
        ),
    ]
