# Generated by Django 4.2.28 on 2026-03-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '1021_connector_pairing_session'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='connectorpairingsession',
            new_name='sales_conne_device__f7d47d_idx',
            old_name='sales_conne_device__7ef5e5_idx',
        ),
        migrations.RenameIndex(
            model_name='connectorpairingsession',
            new_name='sales_conne_pairing_918072_idx',
            old_name='sales_conne_pairing_5f5f23_idx',
        ),
        migrations.RenameIndex(
            model_name='connectorpairingsession',
            new_name='sales_conne_expires_033f3f_idx',
            old_name='sales_conne_expires_3ca774_idx',
        ),
    ]
