# Generated by Django 4.2.30 on 2026-04-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '1025_refund_refunditem'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'outlet', 'is_void', 'status', 'created_at'], name='sale_report_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'outlet', 'created_at'], name='sale_tenant_outlet_date_idx'),
        ),
    ]
