# Generated by Django 4.2.7 on 2026-05-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '1026_add_composite_report_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at'], 'verbose_name': 'Refund', 'verbose_name_plural': 'Refunds'},
        ),
        migrations.AlterModelOptions(
            name='refunditem',
            options={'verbose_name': 'Refund Item', 'verbose_name_plural': 'Refund Items'},
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='sales_refun_tenant__c3cb6d_idx',
            old_name='sales_refund_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='sales_refun_outlet__92e913_idx',
            old_name='sales_refund_outlet_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='sales_refun_origina_54c88f_idx',
            old_name='sales_refund_sale_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='sales_refun_created_ad8685_idx',
            old_name='sales_refund_created_idx',
        ),
        migrations.RenameIndex(
            model_name='refunditem',
            new_name='sales_refun_refund__378c57_idx',
            old_name='sales_refunditem_refund_idx',
        ),
        migrations.RenameIndex(
            model_name='refunditem',
            new_name='sales_refun_origina_b9df3e_idx',
            old_name='sales_refunditem_item_idx',
        ),
        migrations.AlterField(
            model_name='refund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='original_sale',
            field=models.ForeignKey(help_text='The sale being (partially) refunded', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Money'), ('tab', 'Tab'), ('credit', 'Credit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='stock_restored',
            field=models.BooleanField(default=False, help_text='Whether stock was restored to inventory'),
        ),
        migrations.AlterField(
            model_name='refunditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
