# Generated by Django 4.2.7 on 2026-06-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '1028_add_sale_payment_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Money'), ('airtel', 'Airtel Money'), ('tnm', 'TNM Money'), ('first_capital_bank', 'First Capital Bank'), ('national_bank', 'National Bank'), ('standard_bank', 'Standard Bank'), ('other', 'Other'), ('tab', 'Tab'), ('credit', 'Credit'), ('mixed', 'Mixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_lines',
            field=models.JSONField(blank=True, default=list, help_text='Detailed payment lines for split payments', null=True),
        ),
    ]
