# Generated by Django 4.2.7 on 2026-06-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '1029_alter_refund_payment_method_alter_sale_payment_lines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Money'), ('airtel', 'Airtel Money'), ('tnm', 'TNM Money'), ('first_capital_bank', 'First Capital Bank'), ('national_bank', 'National Bank'), ('standard_bank', 'Standard Bank'), ('other', 'Other'), ('tab', 'Tab'), ('credit', 'Credit'), ('mixed', 'Mixed')], default='cash', max_length=20),
        ),
    ]
