# Generated by Django 4.2.28 on 2026-02-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_alter_printer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='business_type',
            field=models.CharField(choices=[('wholesale_and_retail', 'Wholesale and Retail'), ('restaurant', 'Restaurant'), ('bar', 'Bar')], default='wholesale_and_retail', help_text='Business type for this outlet', max_length=30),
        ),
        migrations.AddIndex(
            model_name='outlet',
            index=models.Index(fields=['tenant', 'business_type'], name='outlets_out_tenant__3d8a20_idx'),
        ),
    ]
