# Generated by Django 4.2.28 on 2026-02-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlets", "0006_outlet_business_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlet",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
