# Generated by Django 4.2.28 on 2026-02-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0007_outlet_settings'),
    ]

    operations = [
    ]
