# Generated by Django 4.2.28 on 2026-04-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0011_outlet_distribution_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='distribution_active',
        ),
    ]
