# Generated by Django 4.2.7 on 2026-07-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_phase2_safe_apply'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importapplyerror',
            new_name='imports_imp_batch_i_5923c9_idx',
            old_name='imports_imp_batch_i_d72d43_idx',
        ),
        migrations.RenameIndex(
            model_name='importapplyerror',
            new_name='imports_imp_batch_i_6b3d2f_idx',
            old_name='imports_imp_batch_i_a38f41_idx',
        ),
        migrations.RenameIndex(
            model_name='importapplyerror',
            new_name='imports_imp_error_c_461a2d_idx',
            old_name='imports_imp_error_c_9f9fc5_idx',
        ),
        migrations.RenameIndex(
            model_name='importauditevent',
            new_name='imports_imp_batch_i_e067b1_idx',
            old_name='imports_imp_batch_i_7dd0e1_idx',
        ),
        migrations.RenameIndex(
            model_name='importauditevent',
            new_name='imports_imp_event_t_d7e99a_idx',
            old_name='imports_imp_event_t_7f602d_idx',
        ),
        migrations.RenameIndex(
            model_name='importbatch',
            new_name='imports_imp_tenant__403f52_idx',
            old_name='imports_imp_tenant__3c704a_idx',
        ),
        migrations.RenameIndex(
            model_name='importbatch',
            new_name='imports_imp_tenant__8046a8_idx',
            old_name='imports_imp_tenant__983c65_idx',
        ),
        migrations.RenameIndex(
            model_name='importbatch',
            new_name='imports_imp_idempot_9df17c_idx',
            old_name='imports_imp_idempot_3ed4be_idx',
        ),
        migrations.RenameIndex(
            model_name='importrowresult',
            new_name='imports_imp_batch_i_72f674_idx',
            old_name='imports_imp_batch_i_0948b7_idx',
        ),
        migrations.RenameIndex(
            model_name='importrowresult',
            new_name='imports_imp_batch_i_2cc354_idx',
            old_name='imports_imp_batch_i_651d9f_idx',
        ),
    ]
