# Generated by Django 4.2.7 on 2026-07-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_rename_imports_imp_batch_i_d72d43_idx_imports_imp_batch_i_5923c9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='imports/%Y/%m/%d/'),
        ),
    ]
