# Generated by Django 4.2.7 on 2026-07-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_alter_importbatch_source_file_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='sync_mode',
            field=models.CharField(choices=[('upsert_adjust', 'Upsert + Adjust'), ('inventory_sync', 'Inventory Sync')], default='upsert_adjust', max_length=50),
        ),
    ]
