# Generated by Django 4.2.7 on 2026-07-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_importstockmutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(
                choices=[
                    ('uploaded', 'Uploaded'),
                    ('preview_ready', 'Preview Ready'),
                    ('approved', 'Approved'),
                    ('applying', 'Applying'),
                    ('applied', 'Applied'),
                    ('cancelled', 'Cancelled'),
                    ('failed', 'Failed'),
                ],
                default='uploaded',
                max_length=50,
            ),
        ),
    ]
