# Generated by Django 4.2.7 on 2026-07-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_alter_importbatch_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importstockmutation',
            new_name='imports_imp_batch_i_1498bf_idx',
            old_name='imports_imp_batch_i_0ee9db_idx',
        ),
        migrations.RenameIndex(
            model_name='importstockmutation',
            new_name='imports_imp_product_a4d828_idx',
            old_name='imports_imp_product_848dfa_idx',
        ),
        migrations.RenameIndex(
            model_name='importstockmutation',
            new_name='imports_imp_created_c2d3b2_idx',
            old_name='imports_imp_created_f8e64d_idx',
        ),
    ]
