# Generated by Django 4.2.7 on 2026-08-03 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stocktakeitem_count_tracking'),
        ('imports', '0008_rename_imports_imp_batch_i_0ee9db_idx_imports_imp_batch_i_1498bf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='stock_take',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='inventory.stocktake'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='entity_type',
            field=models.CharField(choices=[('products', 'Products'), ('stock_take', 'Stock Take')], default='products', max_length=50),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['tenant', 'stock_take', 'created_at'], name='imports_imp_tenant__7ea628_idx'),
        ),
    ]
