# Generated by Django 4.2.7 on 2026-08-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0009_importbatch_stock_take_alter_importbatch_entity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importstockmutation',
            name='after_product_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importstockmutation',
            name='before_product_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importstockmutation',
            name='catalog_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importstockmutation',
            name='product_created',
            field=models.BooleanField(default=False),
        ),
    ]
